# Generated by Django 3.1.5 on 2021-01-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('released', models.BooleanField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length='64')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('sheet_music', models.FilePathField(blank=True, path='/Users/nated/OneDrive/music', recursive=True)),
                ('lyrics', models.FilePathField(blank=True, path='/Users/nated/OneDrive/music', recursive=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discography.album')),
                ('artists', models.ManyToManyField(to='Discography.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('audacity', 'audacity'), ('mix', 'mix'), ('master', 'master'), ('loop-core-list', 'loop-core-list'), ('wav', 'wav'), ('audacity', 'audacity')], max_length=64)),
                ('path', models.FilePathField(blank=True, path='/Users/nated/OneDrive/music', recursive=True)),
                ('notes', models.ImageField(blank=True, upload_to='')),
                ('instruments', models.ManyToManyField(to='Discography.Instrument')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discography.song')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='bands',
            field=models.ManyToManyField(to='Discography.Band'),
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Discography.song')),
                ('notes', models.ImageField(blank=True, upload_to='')),
                ('notes_completed', models.BooleanField()),
                ('covered_instruments', models.ManyToManyField(to='Discography.Instrument')),
            ],
            bases=('Discography.song',),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Discography.song')),
                ('beats_per_minute_upper', models.IntegerField()),
                ('beats_per_minute_lower', models.IntegerField()),
                ('written_instruments', models.ManyToManyField(to='Discography.Instrument')),
            ],
            bases=('Discography.song',),
        ),
    ]
